# 판다스 데이터 분석

In [187]:
import numpy as np
import pandas as pd 

### 시리즈(Series)

In [188]:
s = pd.Series([9904312, 3448737, 2890451, 2466052],
                index=["서울", "부산", "인천", "대구"])
s

서울    9904312
부산    3448737
인천    2890451
대구    2466052
dtype: int64

In [189]:
# numpy
x = np.array([9904312, 3448737, 2890451, 2466052])
x

array([9904312, 3448737, 2890451, 2466052])

In [190]:
pd.Series(range(10, 14))

0    10
1    11
2    12
3    13
dtype: int64

In [191]:
s.index

Index(['서울', '부산', '인천', '대구'], dtype='object')

In [192]:
s.values

array([9904312, 3448737, 2890451, 2466052], dtype=int64)

In [193]:
s.name = "인구"
s.index.name = "도시"
s

도시
서울    9904312
부산    3448737
인천    2890451
대구    2466052
Name: 인구, dtype: int64

### 시리즈 연산

In [194]:
s / 1000000

도시
서울    9.904312
부산    3.448737
인천    2.890451
대구    2.466052
Name: 인구, dtype: float64

### 시리즈 인덱싱

In [195]:
s[1], s['부산']

(3448737, 3448737)

In [196]:
# 자료의 순서를 바꾸거나 특정한 자료만 선택할 수 있다
s[[0, 3, 1]]

도시
서울    9904312
대구    2466052
부산    3448737
Name: 인구, dtype: int64

In [197]:
s[["서울", "대구", "부산"]]

도시
서울    9904312
대구    2466052
부산    3448737
Name: 인구, dtype: int64

In [198]:
s[(250e4 < s) & (s < 500e4)]

도시
부산    3448737
인천    2890451
Name: 인구, dtype: int64

In [199]:
s[1:3]

도시
부산    3448737
인천    2890451
Name: 인구, dtype: int64

In [200]:
# 부산에서 대구까지 (대구도 포함)
s["부산":"대구"]

도시
부산    3448737
인천    2890451
대구    2466052
Name: 인구, dtype: int64

In [201]:
# 만약 라벨 값이 영문 문자열인 경우에는 점(.)을 이용
s0 = pd.Series(range(3), index=["a", "b", "c"])
s0

a    0
b    1
c    2
dtype: int64

In [202]:
s0.a

0

In [203]:
s0.b

1

### 시리즈와 딕셔너리 자료형

In [204]:
"서울" in s

True

In [205]:
"대전" in s

False

In [206]:
for k, v in s.items():
    print(f"{k} = {v}")

서울 = 9904312
부산 = 3448737
인천 = 2890451
대구 = 2466052


In [207]:
s2 = pd.Series({"서울": 9631482, "부산": 3393191, "인천": 2632035, "대전": 1490158})
s2

서울    9631482
부산    3393191
인천    2632035
대전    1490158
dtype: int64

In [208]:
s2 = pd.Series({"서울": 9631482, "부산": 3393191, "인천": 2632035, "대전": 1490158},
               index=["부산", "서울", "인천", "대전"])
s2

부산    3393191
서울    9631482
인천    2632035
대전    1490158
dtype: int64

In [209]:
s

도시
서울    9904312
부산    3448737
인천    2890451
대구    2466052
Name: 인구, dtype: int64

In [210]:
ds = s - s2
ds

대구         NaN
대전         NaN
부산     55546.0
서울    272830.0
인천    258416.0
dtype: float64

In [211]:
s.values - s2.values

array([ 6511121, -6182745,   258416,   975894], dtype=int64)

In [212]:
ds.notnull()

대구    False
대전    False
부산     True
서울     True
인천     True
dtype: bool

In [213]:
ds[ds.notnull()]

부산     55546.0
서울    272830.0
인천    258416.0
dtype: float64

In [214]:
# 인구 증가율(%)
rs = (s - s2) / s2 * 100
rs = rs[rs.notnull()]
rs

부산    1.636984
서울    2.832690
인천    9.818107
dtype: float64

In [215]:
# 데이터 갱신
rs["부산"] = 1.63
rs

부산    1.630000
서울    2.832690
인천    9.818107
dtype: float64

In [216]:
# 데이터 추가
rs["대구"] = 1.41
rs

부산    1.630000
서울    2.832690
인천    9.818107
대구    1.410000
dtype: float64

In [217]:
del rs["서울"]
rs

부산    1.630000
인천    9.818107
대구    1.410000
dtype: float64

#### 연습문제 4.1.1

In [218]:
# (1)
x = pd.Series(np.arange(1, 6), index=['a1', 'a2', 'a3', 'a4', 'a5'])
y = pd.Series(np.linspace(10, 50, 5), index=['b1', 'b2', 'b3', 'b4', 'b5'])
x, y

(a1    1
 a2    2
 a3    3
 a4    4
 a5    5
 dtype: int32,
 b1    10.0
 b2    20.0
 b3    30.0
 b4    40.0
 b5    50.0
 dtype: float64)

In [219]:
x['a3'] + y

b1    13.0
b2    23.0
b3    33.0
b4    43.0
b5    53.0
dtype: float64

In [220]:
y['b5'] / x

a1    50.000000
a2    25.000000
a3    16.666667
a4    12.500000
a5    10.000000
dtype: float64

In [221]:
x['a2'] * y

b1     20.0
b2     40.0
b3     60.0
b4     80.0
b5    100.0
dtype: float64

In [222]:
y['b3'] - x

a1    29.0
a2    28.0
a3    27.0
a4    26.0
a5    25.0
dtype: float64

### 데이터프레임(DataFrame)
- 우선 하나의 열이 되는 데이터를 리스트나 일차원 배열을 준비한다.
- 이 각각의 열에 대한 이름(라벨)을 키로 가지는 딕셔너리를 만든다.
- 이 데이터를 DataFrame 클래스 생성자에 넣는다. 동시에 열방향 인덱스는 columns 인수로, 행방향 인덱스는 index 인수로 지정한다.

In [223]:
data = {
    "2015": [9904312, 3448737, 2890451, 2466052],
    "2010": [9631482, 3393191, 2632035, 2431774],
    "2005": [9762546, 3512547, 2517680, 2456016],
    "2000": [9853972, 3655437, 2466338, 2473990],
    "지역": ["수도권", "경상권", "수도권", "경상권"],
    "2010-2015 증가율": [0.0283, 0.0163, 0.0982, 0.0141]
}
columns = ["지역", "2015", "2010", "2005", "2000", "2010-2015 증가율"]
index = ["서울", "부산", "인천", "대구"]
df = pd.DataFrame(data, index=index, columns=columns)
df

지역     2015     2010     2005     2000  2010-2015 증가율
서울  수도권  9904312  9631482  9762546  9853972         0.0283
부산  경상권  3448737  3393191  3512547  3655437         0.0163
인천  수도권  2890451  2632035  2517680  2466338         0.0982
대구  경상권  2466052  2431774  2456016  2473990         0.0141

In [224]:
df.values

array([['수도권', 9904312, 9631482, 9762546, 9853972, 0.0283],
       ['경상권', 3448737, 3393191, 3512547, 3655437, 0.0163],
       ['수도권', 2890451, 2632035, 2517680, 2466338, 0.0982],
       ['경상권', 2466052, 2431774, 2456016, 2473990, 0.0141]], dtype=object)

In [225]:
df.columns

Index(['지역', '2015', '2010', '2005', '2000', '2010-2015 증가율'], dtype='object')

In [226]:
df.index

Index(['서울', '부산', '인천', '대구'], dtype='object')

In [227]:
df.index.name = "도시"
df.columns.name = "특성"
df

특성   지역     2015     2010     2005     2000  2010-2015 증가율
도시                                                        
서울  수도권  9904312  9631482  9762546  9853972         0.0283
부산  경상권  3448737  3393191  3512547  3655437         0.0163
인천  수도권  2890451  2632035  2517680  2466338         0.0982
대구  경상권  2466052  2431774  2456016  2473990         0.0141

#### 연습문제 4.1.2

In [228]:
data = {
    '이름': ['제이미 바디', '칼버트 르윈', '모하메드 살라', '손흥민', '패트릭 뱀포드'],
    '득점': [8, 8, 8, 8, 7],
    '도움': [1, 1, 0, 2, 0],
    '슈팅': [13, 19, 21, 15 ,20],
    '경기당 득점 수': [1.143, 1, 1, 1, 0.875]
}
index = ["잉글랜드", "잉글랜드", "이집트", "대한민국", "잉글랜드"]
my_df = pd.DataFrame(data, index=index)
my_df.index.name = "국적"
my_df.columns.name = "정보"
my_df

정보         이름  득점  도움  슈팅  경기당 득점 수
국적                                 
잉글랜드   제이미 바디   8   1  13     1.143
잉글랜드   칼버트 르윈   8   1  19     1.000
이집트   모하메드 살라   8   0  21     1.000
대한민국      손흥민   8   2  15     1.000
잉글랜드  패트릭 뱀포드   7   0  20     0.875

### 열 데이터의 갱신, 추가, 삭제

In [229]:
# "2010-2015 증가율"이라는 이름의 열 추가
df["2010-2015 증가율"] = df["2010-2015 증가율"] * 100
df

특성   지역     2015     2010     2005     2000  2010-2015 증가율
도시                                                        
서울  수도권  9904312  9631482  9762546  9853972           2.83
부산  경상권  3448737  3393191  3512547  3655437           1.63
인천  수도권  2890451  2632035  2517680  2466338           9.82
대구  경상권  2466052  2431774  2456016  2473990           1.41

In [230]:
# "2005-2010 증가율"이라는 이름의 열 추가
df["2005-2010 증가율"] = ((df["2010"] - df["2005"]) / df["2005"] * 100).round(2)
df

특성   지역     2015     2010     2005     2000  2010-2015 증가율  2005-2010 증가율
도시                                                                       
서울  수도권  9904312  9631482  9762546  9853972           2.83          -1.34
부산  경상권  3448737  3393191  3512547  3655437           1.63          -3.40
인천  수도권  2890451  2632035  2517680  2466338           9.82           4.54
대구  경상권  2466052  2431774  2456016  2473990           1.41          -0.99

In [231]:
# "2010-2015 증가율"이라는 이름의 열 삭제
del df["2010-2015 증가율"]
df

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시                                                        
서울  수도권  9904312  9631482  9762546  9853972          -1.34
부산  경상권  3448737  3393191  3512547  3655437          -3.40
인천  수도권  2890451  2632035  2517680  2466338           4.54
대구  경상권  2466052  2431774  2456016  2473990          -0.99

### 열 인덱싱

In [232]:
# 하나의 열만 인덱싱하면 시리즈가 반환된다.
df["지역"]

도시
서울    수도권
부산    경상권
인천    수도권
대구    경상권
Name: 지역, dtype: object

In [233]:
# 여러개의 열을 인덱싱하면 부분적인 데이터프레임이 반환된다.
df[["2010", "2015"]]

특성     2010     2015
도시                  
서울  9631482  9904312
부산  3393191  3448737
인천  2632035  2890451
대구  2431774  2466052

In [234]:
# 2010이라는 열을 반환하면서 데이터프레임 자료형을 유지
df[["2010"]]

특성     2010
도시         
서울  9631482
부산  3393191
인천  2632035
대구  2431774

In [235]:
df["2010"]

도시
서울    9631482
부산    3393191
인천    2632035
대구    2431774
Name: 2010, dtype: int64

In [236]:
type(df["2010"])

pandas.core.series.Series

In [237]:
df2 = pd.DataFrame(np.arange(12).reshape(3, 4))
df2

0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [238]:
df2[0]

0    0
1    4
2    8
Name: 0, dtype: int32

### 행 인덱싱

In [239]:
df

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시                                                        
서울  수도권  9904312  9631482  9762546  9853972          -1.34
부산  경상권  3448737  3393191  3512547  3655437          -3.40
인천  수도권  2890451  2632035  2517680  2466338           4.54
대구  경상권  2466052  2431774  2456016  2473990          -0.99

In [240]:
df[:1]

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시                                                        
서울  수도권  9904312  9631482  9762546  9853972          -1.34

In [241]:
df[:'서울']

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시                                                        
서울  수도권  9904312  9631482  9762546  9853972          -1.34

In [242]:
df["서울":"부산"]

특성   지역     2015     2010     2005     2000  2005-2010 증가율
도시                                                        
서울  수도권  9904312  9631482  9762546  9853972          -1.34
부산  경상권  3448737  3393191  3512547  3655437          -3.40

### 개별 데이터 인덱싱

In [243]:
# frame[열][행]
df['2015']['서울']

9904312

#### 연습문제 4.1.3

In [244]:
data = {
    '국어': [80, 90, 70, 30],
    '영어': [90, 70, 60, 40],
    '수학': [90, 60, 80, 70]
}
columns = ['국어', '영어', '수학']
index = ['춘향', '몽룡', '향단', '방자']
df3 = pd.DataFrame(data, index=index, columns=columns)
df3

국어  영어  수학
춘향  80  90  90
몽룡  90  70  60
향단  70  60  80
방자  30  40  70

In [245]:
# (1) 모든 학생의 수학 점수를 시리즈로 나타낸다.
df3['수학']

춘향    90
몽룡    60
향단    80
방자    70
Name: 수학, dtype: int64

In [246]:
# (2) 모든 학생의 국어와 영어 점수를 데이터 프레임으로 나타낸다.
df3[['국어', '영어']]

국어  영어
춘향  80  90
몽룡  90  70
향단  70  60
방자  30  40

In [247]:
# (3) 모든 학생의 각 과목 평균 점수를 새로운 열로 추가한다.
df3['평균'] = ((df3['국어'] + df3['영어'] + df3['수학']) / 3).round(2)
df3

국어  영어  수학     평균
춘향  80  90  90  86.67
몽룡  90  70  60  73.33
향단  70  60  80  70.00
방자  30  40  70  46.67

In [248]:
# (4) 방자의 영어 점수를 80점으로 수정하고 평균 점수도 다시 계산한다.
df3['영어']['방자'] = 80
df3['평균'] = ((df3['국어'] + df3['영어'] + df3['수학']) / 3).round(2)
df3

국어  영어  수학     평균
춘향  80  90  90  86.67
몽룡  90  70  60  73.33
향단  70  60  80  70.00
방자  30  80  70  60.00

In [251]:
# (5) 춘향의 점수를 데이터프레임으로 나타낸다.
df3[:'춘향'].T

춘향
국어  80.00
영어  90.00
수학  90.00
평균  86.67

In [250]:
# (6) 향단의 점수를 시리즈로 나타낸다.
trans_df3 = df3.T
trans_df3['향단']

국어    70.0
영어    60.0
수학    80.0
평균    70.0
Name: 향단, dtype: float64