# Numpy

### Numpy Array

In [4]:
# 리스트와 넘파이 array 속도 비교
import numpy as np
np_arr = np.arange(100000)
nu_list = [i for i in range(100000)]

In [5]:
%%time
for i in range(100):
    sum(nu_list)

Wall time: 147 ms


In [6]:
%%time 
for i in range(100):
    np.sum(np_arr)

Wall time: 5 ms


### 1차원 배열 만들기

In [7]:
ar = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
type(ar)

numpy.ndarray

In [9]:
ar.shape

(10,)

### 벡터화 연산

In [12]:
al = [2*i for i in range(1, 11)]
al

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

In [13]:
2 * ar

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [14]:
2 * al

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

In [15]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

In [16]:
2 * a + b

array([12, 24, 36])

In [17]:
a == 2

array([False,  True, False])

In [18]:
b  > 15

array([False,  True,  True])

In [19]:
(a == 2) & (b > 10)

array([False,  True, False])

### 2차원 배열

In [21]:
c = np.array([[0, 1, 2], [3, 4, 5]])      # 2 x 3 array
c

array([[0, 1, 2],
       [3, 4, 5]])

In [22]:
c.shape

(2, 3)

In [23]:
# 연습문제 1
my_arr = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])
my_arr

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [24]:
np.arange(10, 90, 10).reshape(2, -1)

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [26]:
# 2 x 3 x 4 array
d = np.array([[[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]],
                [[11, 12, 13, 14],
                [15, 16, 17, 18],
                [19, 20, 21, 22]]])
d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]]])

In [28]:
# ndim: ?차원
d.shape, d.ndim

((2, 3, 4), 3)

### 배열의 인덱싱

In [29]:
a = np.array([0, 1, 2, 3, 4])
a[2]

2

In [30]:
a[-1]

4

In [32]:
a = np.array([[1, 2, 3], [3, 4, 5]])

In [33]:
a[1, 0]

3

### 배열 슬라이싱

In [34]:
a = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [35]:
a[:, 1:3]

array([[1, 2],
       [5, 6]])

In [38]:
# 연습문제 2
m = np.array([[0, 1, 2, 3, 4],
            [5, 6, 7, 8, 9],
            [10, 11, 12, 13, 14]])
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [39]:
# (1)
m[1, 2]

7

In [40]:
# (2)
m[-1, -1]

14

In [42]:
# (3)
m[1, 1:3]

array([6, 7])

In [43]:
# (4)
m[1:3, 2]

array([ 7, 12])

In [47]:
# (5)
m[:2, 3:]

array([[3, 4],
       [8, 9]])

### 배열 인덱싱

In [48]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
idx = np.array([True, False, True, False, True, 
                False, True, False, True, False])
a[idx]

array([0, 2, 4, 6, 8])

In [49]:
a % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [50]:
a[a % 2 == 0]

array([0, 2, 4, 6, 8])

In [51]:
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([0, 2, 4, 6, 8])
a[idx]

array([11, 33, 55, 77, 99])

In [52]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [53]:
a[:, [True, False, False, True]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [54]:
a[[2, 0, 1], :]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [55]:
# 연습문제 3
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [56]:
# (1)
x[x % 3 == 0]

array([ 3,  6,  9, 12, 15, 18])

In [57]:
# (2)
x[x % 4 == 1]

array([ 1,  5,  9, 13, 17])

In [58]:
# (3)
x[(x % 3 == 0) & (x % 4 == 1)]

array([9])