# 배열의 생성과 변형

In [56]:
import numpy as np 

In [57]:
x = np.array([1, 2, 3])
x.dtype

dtype('int32')

In [58]:
x = np.array([1.0, 2.0, 3.0])
x.dtype

dtype('float64')

In [59]:
x = np.array([1, 2, 3.0])
x.dtype

dtype('float64')

In [60]:
x = np.array([1, 2, 3], dtype='float32')
x.dtype

dtype('float32')

### Inf와 NaN

In [61]:
np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])

array([  0.,  inf, -inf,  nan])

In [62]:
np.log(0)

-inf

In [63]:
np.exp(-np.inf)

0.0

### 배열 생성

In [64]:
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [65]:
a.dtype

dtype('float64')

In [109]:
# zeros함수로 생성한 array의 기본형은 float
b = np.zeros((2, 3))
b, b.dtype

(array([[0., 0., 0.],
        [0., 0., 0.]]),
 dtype('float64'))

In [67]:
# 0-배열을 5행 2열로 출력
c = np.zeros((5, 2), dtype="int")
c

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [68]:
c.dtype

dtype('int32')

In [69]:
np.ones(4)

array([1., 1., 1., 1.])

In [70]:
np.ones_like(b)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [71]:
d = np.empty((4, 3))
d

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [72]:
# 0 .. n-1
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
# 시작, 끝(포함하지 않음), 단계
np.arange(3, 21, 2)

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [74]:
# 시작, 끝(포함), 갯수
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

In [75]:
np.logspace(0.1, 1, 10)

array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

In [76]:
np.log(np.logspace(0.1, 1, 10))

array([0.23025851, 0.46051702, 0.69077553, 0.92103404, 1.15129255,
       1.38155106, 1.61180957, 1.84206807, 2.07232658, 2.30258509])

### 전치 연산 (Transpose)

In [77]:
# 2 x 3 array
A = np.array([[1, 2, 3], [4, 5, 6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [78]:
# 3 x 2 array
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [79]:
A.T @ A

array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]])

In [80]:
A @ A.T

array([[14, 32],
       [32, 77]])

In [81]:
np.dot(A.T, A)

array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]])

In [82]:
np.dot(A, A.T)

array([[14, 32],
       [32, 77]])

### 배열의 크기 변형

In [83]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [84]:
b = a.reshape(3, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [85]:
a.reshape(3, -1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [86]:
a.reshape(-1, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [87]:
a.reshape(3, 2, -1)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [88]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [89]:
b.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [90]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [91]:
x.reshape(1, -1)

array([[0, 1, 2, 3, 4]])

In [92]:
x.reshape(5, 1)

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [93]:
x[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4]])

### 배열 연결

In [94]:
a1 = np.ones((2, 3))
a1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [95]:
a2 = np.zeros((2, 2))
a2

array([[0., 0.],
       [0., 0.]])

In [96]:
np.hstack([a1, a2])

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [97]:
b1 = np.ones((2, 3))
b1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [98]:
b2 = np.zeros((3, 3))
b2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [99]:
np.vstack([b1, b2])

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

#### 연습문제 3.2.1

In [100]:
x1 = np.zeros((3, 3))
x2 = np.ones((3, 2))
x = np.hstack([x1, x2])
x

array([[0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.]])

In [101]:
y1 = np.linspace(10, 150, 15)
y = y1.reshape(3, -1)
y

array([[ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [102]:
X = np.vstack([x, y])
X

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [103]:
Y = np.vstack([X, X])
Y

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

### 2차원 그리드 포인트 생성

In [104]:
x = np.arange(3)
x

array([0, 1, 2])

In [105]:
y = np.arange(5)
y

array([0, 1, 2, 3, 4])

In [106]:
X, Y = np.meshgrid(x, y)
X

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [107]:
Y

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [108]:
[list(zip(x, y)) for x, y in zip(X, Y)]

[[(0, 0), (1, 0), (2, 0)],
 [(0, 1), (1, 1), (2, 1)],
 [(0, 2), (1, 2), (2, 2)],
 [(0, 3), (1, 3), (2, 3)],
 [(0, 4), (1, 4), (2, 4)]]