# 배열의 연산

### 벡터화 연산

In [1]:
import numpy as np 

In [2]:
x = np.arange(1, 10001)
y = np.arange(10001, 20001)

In [3]:
%%time 
z = np.zeros_like(x)
for i in range(10000):
    z[i] = x[i] + y[i]

Wall time: 6 ms


In [4]:
%%time 
z = x + y

Wall time: 0 ns


In [5]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
a == b

array([False,  True, False,  True])

In [6]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
c = np.array([1, 2, 3, 4])

In [7]:
# 배열의 모든 원소가 다 같은지 알고 싶다면 all 명령을 사용하면 된다
np.all(a == b)

False

In [8]:
np.all(a == c)

True

In [9]:
a = np.arange(1, 11)
# 자연로그
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [10]:
# 상용로그
np.log10(a)

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ,
       0.77815125, 0.84509804, 0.90308999, 0.95424251, 1.        ])

### 스칼라와 벡터/행렬의 곱셈

In [11]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
100 * x

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [13]:
x = np.arange(12).reshape(3, -1)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [14]:
100 * x

array([[   0,  100,  200,  300],
       [ 400,  500,  600,  700],
       [ 800,  900, 1000, 1100]])

### 브로드캐스팅

In [15]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [16]:
y = np.ones_like(x)
y

array([1, 1, 1, 1, 1])

In [17]:
x + y

array([1, 2, 3, 4, 5])

In [18]:
x + 1

array([1, 2, 3, 4, 5])

### 차원 축소

In [19]:
x = np.array([[1, 1], [2, 2]])
x

array([[1, 1],
       [2, 2]])

In [20]:
np.sum(x)

6

In [21]:
# 열 끼리의 합
np.sum(x, axis=0)

array([3, 3])

In [22]:
# 행 끼리의 합
np.sum(x, axis=1)

array([2, 4])

#### 연습문제 3.3.1

In [26]:
x = np.linspace(1.0, 10.0, 30).reshape(5, 6).round(2)
x

array([[ 1.  ,  1.31,  1.62,  1.93,  2.24,  2.55],
       [ 2.86,  3.17,  3.48,  3.79,  4.1 ,  4.41],
       [ 4.72,  5.03,  5.34,  5.66,  5.97,  6.28],
       [ 6.59,  6.9 ,  7.21,  7.52,  7.83,  8.14],
       [ 8.45,  8.76,  9.07,  9.38,  9.69, 10.  ]])

In [27]:
# (1) 전체의 최댓값
x.max()

10.0

In [28]:
# (2) 각 행의 합
np.sum(x, axis=1)

array([10.65, 21.81, 33.  , 44.19, 55.35])

In [29]:
# (3) 각 행의 최댓값
x.min(axis=1)

array([1.  , 2.86, 4.72, 6.59, 8.45])

In [30]:
# (4) 각 열의 평균
np.average(x, axis=0)

array([4.724, 5.034, 5.344, 5.656, 5.966, 6.276])

In [31]:
# (5) 각 열의 최솟값
x.min(axis=0)

array([1.  , 1.31, 1.62, 1.93, 2.24, 2.55])

### 정렬

In [32]:
a = np.array([[4,  3,  5,  7],
              [1, 12, 11,  9],
              [2, 15,  1, 14]])
a

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [33]:
np.sort(a)

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [35]:
# 각각의 행을 정렬
np.sort(a, axis=1)

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [36]:
# 각각의 열을 정렬
np.sort(a, axis=0)

array([[ 1,  3,  1,  7],
       [ 2, 12,  5,  9],
       [ 4, 15, 11, 14]])

In [37]:
# a가 바뀌지 않는다
a

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [38]:
# sort메서드는 자체변화(in-place) 메서드이므로 주의!
a.sort()
a

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [39]:
# 자료를 정렬하는 것이 아니라 순서만 알고 싶다면 argsort 명령을 사용한다
a = np.array([42, 38, 12, 25])
j = np.argsort(a)
j

array([2, 3, 1, 0], dtype=int64)