# 난수 발생과 카운팅

In [1]:
import numpy as np

### 시드 설정하기

In [2]:
np.random.rand(5)

array([0.81147019, 0.86753954, 0.57519352, 0.29760063, 0.02301333])

In [3]:
np.random.rand(5)

array([0.945857  , 0.17912201, 0.93476286, 0.32964581, 0.45147808])

In [4]:
np.random.seed(2020)
np.random.rand(5)

array([0.98627683, 0.87339195, 0.50974552, 0.27183571, 0.33691873])

In [5]:
np.random.seed(2020)
np.random.rand(5)

array([0.98627683, 0.87339195, 0.50974552, 0.27183571, 0.33691873])

### 데이터의 순서 바꾸기

In [6]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
# 자체변환(in-place) 메서드
np.random.shuffle(x)
x

array([5, 7, 6, 4, 3, 1, 2, 8, 9, 0])

### 데이터 샘플링

In [8]:
# shuffle 명령과 같다
np.random.choice(5, 5, replace=False)  

array([4, 0, 1, 2, 3])

In [9]:
np.random.choice(5, 3, replace=False)  # 3개만 선택

array([1, 2, 3])

In [10]:
# 선택 확률을 다르게 해서 10개 선택
np.random.choice(5, 10, p=[0.1, 0, 0.3, 0.6, 0])

array([3, 3, 3, 0, 3, 3, 2, 2, 2, 3])

### 난수 생성

In [11]:
np.random.rand(5)

array([0.27212605, 0.81612241, 0.18040797, 0.04298562, 0.81831177])

In [12]:
np.random.randn(10)

array([ 1.06639311,  0.97750987,  0.84762002,  0.62842431, -2.04329806,
       -0.42138737, -0.0905073 ,  0.71308148,  0.09412645, -0.98878783])

In [13]:
np.random.randint(10, size=10)

array([0, 0, 4, 6, 6, 8, 9, 9, 9, 5])

In [14]:
np.random.randint(10, 20, size=10)

array([11, 19, 10, 11, 17, 15, 10, 17, 11, 13])

In [16]:
# 연습문제 3.5.2
price = 10000
tomorrow = price * (1 + np.random.randn(1)/100.)
tomorrow[0]

10036.80509340392

In [17]:
prices = []
price = 10000
for i in range(250):
    tmp = price * (1 + np.random.randn(1)/100.)
    price = tmp[0]
    prices.append(price)
prices[:10]

[9963.45124730348,
 9807.769277573103,
 9720.76764633456,
 9777.07732938137,
 9749.635331706362,
 9742.680717634525,
 9815.426633021876,
 9735.595820980963,
 9800.521354668565,
 9902.130096928284]

### 정수 데이터 카운팅

In [18]:
np.unique([11, 11, 2, 2, 34, 34])

array([ 2, 11, 34])

In [19]:
a = np.array(['a', 'b', 'b', 'c', 'a'])
index, count = np.unique(a, return_counts=True)

In [20]:
index

array(['a', 'b', 'c'], dtype='<U1')

In [21]:
count

array([2, 2, 1], dtype=int64)

In [22]:
np.bincount([1, 1, 2, 2, 2, 3], minlength=6)

array([0, 2, 3, 1, 0, 0], dtype=int64)