# 벡터와 벡터의 곱셈

In [1]:
import numpy as np

In [2]:
x = np.arange(1, 4).reshape(3, 1)
x

array([[1],
       [2],
       [3]])

In [3]:
y = np.arange(4, 7).reshape(3, 1)
y

array([[4],
       [5],
       [6]])

In [4]:
# inner(dot) product 불가 
x.shape, y.shape

((3, 1), (3, 1))

In [5]:
# inner(dot) product 가능
x.T.shape, y.shape

((1, 3), (3, 1))

In [6]:
z =  x.T @ y
z

array([[32]])

In [7]:
z.shape

(1, 1)

In [8]:
z[0, 0]

32

In [9]:
np.dot(x.T, y)

array([[32]])

In [10]:
x = np.arange(1, 7).reshape(2, 3)
x

array([[1, 2, 3],
       [4, 5, 6]])

### 가중합

In [11]:
x @ x.T

array([[14, 32],
       [32, 77]])

#### 연습문제 2.2.1

In [14]:
p = np.array([1000000, 800000, 500000])
n = np.arange(3, 6)
y = np.dot(p, n)
print(f'주식 매수 필요 금액: {y:,}원')

주식 매수 필요 금액: 8,700,000원


#### 연습문제 2.2.4

In [15]:
# (1)
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[1, 2], [3, 4], [5, 6]])
C = A @ B
C

array([[22, 28],
       [49, 64]])

In [16]:
# (2)
D = B @ A
D

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

In [21]:
# (3)
# AB만 계산가능, BA는 불가 
A = np.arange(1, 4)                         # 1 x 3 array
B = np.array([[4, 7], [5, 8], [6, 9]])      # 3 x 2 array
C = A @ B
C

array([32, 50])

In [24]:
# (4)
# AB, BA 둘 다 계산 가능, AB와 BA는 다르다
A = np.arange(1, 5).reshape(2, -1)
B = np.arange(5, 9).reshape(2, -1)
C = A @ B
D = B @ A
C, D

(array([[19, 22],
        [43, 50]]),
 array([[23, 34],
        [31, 46]]))

In [27]:
# (5)
# B는 3 x 3 array, C는 2 x 2 array, 항상 정방행렬이다
A = np.arange(1, 7).reshape(3, -1)
B = A @ A.T
C = A.T @ A
B, C

(array([[ 5, 11, 17],
        [11, 25, 39],
        [17, 39, 61]]),
 array([[35, 44],
        [44, 56]]))

In [29]:
# (6)
# x.T @ x는 스칼라, x @ x.T는 정방행렬
x = np.arange(1, 4).reshape(3, -1)
y1 = x.T @ x
y2 = x @ x.T
y1, y2

(array([[14]]),
 array([[1, 2, 3],
        [2, 4, 6],
        [3, 6, 9]]))