## 연습문제

In [60]:
import numpy as np 

#### 1. 길이가 10인 0-벡터를 만드세요.

In [61]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 2. 길이가 10이며 다섯번째 원소만 1이고 나머지는 0인 벡터를 만드세요.

In [62]:
np.sum(np.eye(1, 10, k=4), axis=0)

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 3. 10부터 49까지의 값을 가지는 벡터를 만드세요.

In [63]:
a = np.arange(10, 50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 4. 위(3번) 벡터의 순서를 바꾸세요.

In [64]:
b = np.sort(a)[::-1]
b

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 5. 0부터 8까지의 값을 가지는 3 x 3 행렬을 만드세요.

In [65]:
c = np.arange(9).reshape(3, -1)
c

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 6. 벡터 \[1, 2, 0, 0, 4, 0\] 에서 원소의 값이 0이 아닌 원소만 선택한 벡터를 만드세요.

In [66]:
d = np.array([1, 2, 0, 0, 4, 0])
d[np.nonzero(d)]

array([1, 2, 4])

#### 7. 3 x 3 단위 행렬(identity matrix)을 만드세요.

In [67]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 8. 난수 원소를 가지는 3 x 3 행렬을 만드세요.

In [68]:
e = np.random.random((3, 3)).round(2)
e

array([[0.92, 0.71, 0.54],
       [0.14, 0.37, 0.67],
       [0.44, 0.43, 0.62]])

#### 9. 위(8번)에서 만든 난수 행렬에서 최대값/최소값 원소를 찾으세요.

In [69]:
print(f'최대값: {e.max()}, 최소값: {e.min()}')

최대값: 0.92, 최소값: 0.14


#### 10. 위(8번)에서 만든 난수 행렬에서 행 평균, 열 평균을 계산하세요.

In [70]:
print(f'행 평균: {np.average(e, axis=1).round(2)}, 열 평균: {np.average(e, axis=0).round(2)}')

행 평균: [0.72 0.39 0.5 ], 열 평균: [0.5  0.5  0.61]
